import { loginController } from "../../controllers/authController.js";
import { requireSignIn } from "../../middlewares/authMiddleware.js";
import userModel from "../../models/userModel.js";
import { hashPassword } from "../../helpers/authHelper.js";

// Mock only the DB boundary
jest.mock("../../models/userModel.js");

// Zhu Shiqi, A0271719X
// Generated by Claude Code
describe("loginController integration with real comparePassword", () => {
  let req, res;

  beforeEach(() => {
    jest.clearAllMocks();
    process.env.JWT_SECRET = "test-secret";

    req = { body: {} };
    res = {
      status: jest.fn().mockReturnThis(),
      send: jest.fn().mockReturnThis(),
    };
  });

  it("rejects wrong password via real bcrypt comparison", async () => {
    const realHash = await hashPassword("correctPassword");

    userModel.findOne = jest.fn().mockResolvedValue({
      _id: "abc123",
      name: "Test User",
      email: "test@example.com",
      password: realHash,
      role: 0,
    });

    req.body = { email: "test@example.com", password: "wrongPassword" };

    await loginController(req, res);

    expect(res.status).toHaveBeenCalledWith(200);
    expect(res.send).toHaveBeenCalledWith(
      expect.objectContaining({ success: false, message: "Invalid Password" })
    );
  });

  it("returns JWT token when password matches via real bcrypt", async () => {
    const realHash = await hashPassword("myPassword");

    userModel.findOne = jest.fn().mockResolvedValue({
      _id: "abc123",
      name: "Test User",
      email: "test@example.com",
      password: realHash,
      phone: "1234567890",
      address: "123 Street",
      role: 0,
    });

    req.body = { email: "test@example.com", password: "myPassword" };

    await loginController(req, res);

    expect(res.status).toHaveBeenCalledWith(200);
    const response = res.send.mock.calls[0][0];
    expect(response.success).toBe(true);
    expect(response.token).toBeDefined();
    expect(response.user).not.toHaveProperty("password");
  });

  it("returned JWT grants access to protected route", async () => {
    const realHash = await hashPassword("myPassword");

    userModel.findOne = jest.fn().mockResolvedValue({
      _id: "abc123",
      name: "Test User",
      email: "test@example.com",
      password: realHash,
      phone: "1234567890",
      address: "123 Street",
      role: 0,
    });

    req.body = { email: "test@example.com", password: "myPassword" };
    await loginController(req, res);

    const token = res.send.mock.calls[0][0].token;
    expect(token).toBeDefined();

    // Use the token to access a protected route via requireSignIn middleware
    const authReq = { headers: { authorization: token } };
    const authRes = { status: jest.fn().mockReturnThis(), send: jest.fn() };
    const next = jest.fn();

    await requireSignIn(authReq, authRes, next);

    expect(next).toHaveBeenCalled();
  });

  it("returns 404 for unregistered email", async () => {
    userModel.findOne = jest.fn().mockResolvedValue(null);

    req.body = { email: "unknown@example.com", password: "somePassword" };

    await loginController(req, res);

    expect(res.status).toHaveBeenCalledWith(404);
    expect(res.send).toHaveBeenCalledWith(
      expect.objectContaining({ success: false, message: "Email is not registered" })
    );
  });

  it.each([
    [{ password: "pass" }, "missing email"],
    [{ email: "a@b.com" }, "missing password"],
    [{}, "missing both"],
  ])("returns 404 for missing credentials (%s)", async (body) => {
    req.body = body;

    await loginController(req, res);

    expect(res.status).toHaveBeenCalledWith(404);
    expect(res.send).toHaveBeenCalledWith(
      expect.objectContaining({ success: false, message: "Invalid email or password" })
    );
  });
});
