import { registerController } from "../../controllers/authController.js";
import userModel from "../../models/userModel.js";

// Mock only the DB boundary
jest.mock("../../models/userModel.js");

// Zhu Shiqi, A0271719X
// Generated by Claude Code, Sonnet 4.6
describe("registerController integration with real hashPassword", () => {
  let req, res, mockSave;

  beforeEach(() => {
    jest.clearAllMocks();

    mockSave = jest.fn().mockImplementation(function () {
      return Promise.resolve(this);
    });
    userModel.mockImplementation(function (data) {
      Object.assign(this, data);
      this.save = mockSave;
    });
    userModel.findOne = jest.fn().mockResolvedValue(null);

    req = { body: {} };
    res = {
      status: jest.fn().mockReturnThis(),
      send: jest.fn().mockReturnThis(),
    };
  });

  it("saves user with hashed password when all fields are valid", async () => {
    const plainPassword = "myPlainPassword";

    req.body = {
      name: "Jane Doe",
      email: "jane@example.com",
      password: plainPassword,
      phone: "1234567890",
      address: "456 Avenue",
      answer: "Tennis",
    };

    await registerController(req, res);

    expect(res.status).toHaveBeenCalledWith(201);
    const response = res.send.mock.calls[0][0];
    expect(response.success).toBe(true);

    // Verify the model was constructed with a bcrypt hash, not plaintext
    const constructorArg = userModel.mock.calls[0][0];
    expect(constructorArg.password).not.toBe(plainPassword);
    expect(constructorArg.password).toMatch(/^\$2b\$/);
  });

  it("returns error when email already exists in the database", async () => {
    userModel.findOne = jest.fn().mockResolvedValue({
      _id: "existingId",
      email: "existing@example.com",
    });

    req.body = {
      name: "Jane Doe",
      email: "existing@example.com",
      password: "password123",
      phone: "1234567890",
      address: "456 Avenue",
      answer: "Tennis",
    };

    await registerController(req, res);

    expect(res.status).toHaveBeenCalledWith(200);
    expect(res.send).toHaveBeenCalledWith(
      expect.objectContaining({
        success: false,
        message: "Already Register please login",
      })
    );
  });

  it.each([
    [
      { email: "a@b.com", password: "pass", phone: "123", address: "addr", answer: "ans" },
      { error: "Name is Required" },
    ],
    [
      { name: "Jane", password: "pass", phone: "123", address: "addr", answer: "ans" },
      { message: "Email is Required" },
    ],
    [
      { name: "Jane", email: "a@b.com", phone: "123", address: "addr", answer: "ans" },
      { message: "Password is Required" },
    ],
    [
      { name: "Jane", email: "a@b.com", password: "pass", address: "addr", answer: "ans" },
      { message: "Phone no is Required" },
    ],
    [
      { name: "Jane", email: "a@b.com", password: "pass", phone: "123", answer: "ans" },
      { message: "Address is Required" },
    ],
    [
      { name: "Jane", email: "a@b.com", password: "pass", phone: "123", address: "addr" },
      { message: "Answer is Required" },
    ],
  ])("returns validation error for missing field", async (body, expectedResponse) => {
    req.body = body;

    await registerController(req, res);

    expect(res.send).toHaveBeenCalledWith(expectedResponse);
    expect(mockSave).not.toHaveBeenCalled();
  });
});
