import { searchProductController } from "../../controllers/productController.js";
import productModel from "../../models/productModel.js";

// Mock only the DB boundary
jest.mock("../../models/productModel.js");

// Zhu Shiqi, A0271719X
// Generated by Claude Code, Sonnet 4.6
describe("searchProductController integration", () => {
  let req, res;

  const makeProduct = (overrides = {}) => ({
    _id: "abc123",
    name: "Laptop Pro",
    description: "A high-performance laptop for professionals",
    price: 1299,
    quantity: 10,
    ...overrides,
  });

  beforeEach(() => {
    jest.clearAllMocks();

    req = { params: {} };
    res = {
      json: jest.fn(),
      status: jest.fn().mockReturnThis(),
      send: jest.fn(),
    };

    // Default: productModel.find(...).select(...) returns []
    productModel.find = jest.fn().mockReturnValue({
      select: jest.fn().mockResolvedValue([]),
    });
  });

  it("returns products matching keyword in name", async () => {
    const laptop = makeProduct();
    productModel.find = jest.fn().mockReturnValue({
      select: jest.fn().mockResolvedValue([laptop]),
    });

    req.params = { keyword: "Laptop" };
    await searchProductController(req, res);

    expect(res.json).toHaveBeenCalledWith([laptop]);
    expect(productModel.find).toHaveBeenCalledWith(
      expect.objectContaining({
        $or: expect.arrayContaining([
          { name: { $regex: "Laptop", $options: "i" } },
        ]),
      })
    );
  });

  it("returns products matching keyword in description", async () => {
    const product = makeProduct({
      name: "Pro Device",
      description: "Powered by the latest quantum chip technology",
    });
    productModel.find = jest.fn().mockReturnValue({
      select: jest.fn().mockResolvedValue([product]),
    });

    req.params = { keyword: "quantum" };
    await searchProductController(req, res);

    expect(res.json).toHaveBeenCalledWith([product]);
    expect(productModel.find).toHaveBeenCalledWith(
      expect.objectContaining({
        $or: expect.arrayContaining([
          { description: { $regex: "quantum", $options: "i" } },
        ]),
      })
    );
  });

  it("search is case-insensitive", async () => {
    const product = makeProduct({ name: "laptop" });
    productModel.find = jest.fn().mockReturnValue({
      select: jest.fn().mockResolvedValue([product]),
    });

    req.params = { keyword: "LAPTOP" };
    await searchProductController(req, res);

    expect(productModel.find).toHaveBeenCalledWith(
      expect.objectContaining({
        $or: expect.arrayContaining([
          { name: { $regex: "LAPTOP", $options: "i" } },
          { description: { $regex: "LAPTOP", $options: "i" } },
        ]),
      })
    );
    expect(res.json).toHaveBeenCalledWith([product]);
  });

  it("partial keyword matches products", async () => {
    const product = makeProduct({ name: "Laptop Pro 15" });
    productModel.find = jest.fn().mockReturnValue({
      select: jest.fn().mockResolvedValue([product]),
    });

    req.params = { keyword: "Lap" };
    await searchProductController(req, res);

    expect(productModel.find).toHaveBeenCalledWith(
      expect.objectContaining({
        $or: expect.arrayContaining([
          { name: { $regex: "Lap", $options: "i" } },
        ]),
      })
    );
    expect(res.json).toHaveBeenCalledWith([product]);
  });

  it("returns empty array when no products match", async () => {
    productModel.find = jest.fn().mockReturnValue({
      select: jest.fn().mockResolvedValue([]),
    });

    req.params = { keyword: "xyznonexistent" };
    await searchProductController(req, res);

    expect(res.json).toHaveBeenCalledWith([]);
    expect(res.status).not.toHaveBeenCalled();
  });

  it("search results exclude photo field", async () => {
    const selectMock = jest.fn().mockResolvedValue([]);
    productModel.find = jest.fn().mockReturnValue({ select: selectMock });

    req.params = { keyword: "test" };
    await searchProductController(req, res);

    expect(selectMock).toHaveBeenCalledWith("-photo");
  });

  it("returns all matching products when multiple products match", async () => {
    const products = [
      makeProduct({ _id: "1", name: "Laptop A" }),
      makeProduct({ _id: "2", name: "Laptop B" }),
      makeProduct({ _id: "3", name: "Gaming Laptop" }),
    ];
    productModel.find = jest.fn().mockReturnValue({
      select: jest.fn().mockResolvedValue(products),
    });

    req.params = { keyword: "laptop" };
    await searchProductController(req, res);

    expect(res.json).toHaveBeenCalledWith(products);
    expect(res.json.mock.calls[0][0]).toHaveLength(3);
  });

  it("handles special regex characters in keyword without crashing", async () => {
    const selectMock = jest.fn().mockResolvedValue([]);
    productModel.find = jest.fn().mockReturnValue({ select: selectMock });

    req.params = { keyword: "(sale)" };
    await searchProductController(req, res);

    // Controller should either return results or return the error response — not throw
    expect(res.json).toHaveBeenCalledWith([]);
  });

});
