import { test, expect } from "@playwright/test";

// Jinhan Wu
// Generated by Claude Code, Sonnet 4.6
//
// End-to-end tests for the app shell:
// Layout (Header + Footer wrapper) · Header · Footer · Spinner · About · Pagenotfound
//
// No database seeding is required — the shell renders correctly regardless of
// whether the product/category API calls succeed, and all page content under
// test is either static (About, 404) or layout-level (Header, Footer).

// ── Shared selectors ──────────────────────────────────────────────────────────

// Header brand link text (includes emoji)
const BRAND = /Virtual Vault/i;

// Footer copyright line
const COPYRIGHT = /All Rights Reserved/i;

// ─────────────────────────────────────────────────────────────────────────────

test.describe("App shell – Layout wraps Header and Footer on every page", () => {

  // ── Test 1 ──────────────────────────────────────────────────────────────────
  // Verifies the full shell structure is intact when the app first loads at "/".
  // Exercises: Layout.js · Header.js · Footer.js · HomePage.js
  test("Home page renders Header brand, nav links, and Footer with its links", async ({
    page,
  }) => {
    // Arrange + Act: navigate to the root route
    await page.goto("/");
    await expect(page).toHaveURL("http://localhost:3000/");

    // Assert – Header brand is present
    await expect(page.getByRole("link", { name: BRAND })).toBeVisible({
      timeout: 10000,
    });

    // Assert – Header navigation links visible for a guest user
    await expect(page.getByRole("link", { name: "Home" })).toBeVisible();
    await expect(page.getByRole("link", { name: "Login" })).toBeVisible();
    await expect(page.getByRole("link", { name: "Register" })).toBeVisible();
    await expect(page.getByRole("link", { name: "Cart" })).toBeVisible();

    // Assert – Footer copyright text and navigation links are present
    await expect(page.getByText(COPYRIGHT)).toBeVisible();
    await expect(page.getByText(/TestingComp/)).toBeVisible();
    await expect(
      page.locator(".footer").getByRole("link", { name: "About" })
    ).toBeVisible();
    await expect(
      page.locator(".footer").getByRole("link", { name: "Contact" })
    ).toBeVisible();
    await expect(
      page.locator(".footer").getByRole("link", { name: "Privacy Policy" })
    ).toBeVisible();

    // Assert – Home page main content is rendered inside the shell
    await expect(
      page.getByRole("heading", { name: "All Products" })
    ).toBeVisible({ timeout: 10000 });
  });

  // ── Test 2 ──────────────────────────────────────────────────────────────────
  // Verifies the shell persists across a client-side navigation from Home to
  // the About page, confirming that every page re-uses Layout correctly.
  // Exercises: Footer.js (link click) · About.js · Layout.js
  test("Header and Footer persist after navigating from Home to About via Footer link", async ({
    page,
  }) => {
    // Arrange: start at home
    await page.goto("/");
    await expect(page.getByRole("link", { name: BRAND })).toBeVisible({
      timeout: 10000,
    });

    // Act: click the About link inside the Footer
    await page.locator(".footer").getByRole("link", { name: "About" }).click();

    // Assert – URL changed to /about
    await expect(page).toHaveURL("http://localhost:3000/about");

    // Assert – About page content is inside the main area
    await expect(page.getByText("Add text")).toBeVisible();

    // Assert – Header is still present (shell persisted through navigation)
    await expect(page.getByRole("link", { name: BRAND })).toBeVisible();
    await expect(page.getByRole("link", { name: "Home" })).toBeVisible();

    // Assert – Footer is still present
    await expect(page.getByText(COPYRIGHT)).toBeVisible();
    await expect(
      page.locator(".footer").getByRole("link", { name: "Contact" })
    ).toBeVisible();
  });

  // ── Test 3 ──────────────────────────────────────────────────────────────────
  // Verifies the 404 / Pagenotfound component is served inside the normal app
  // shell for any unknown route — Layout wraps it just like every other page.
  // Exercises: Pagenotfound.js · Layout.js · Header.js · Footer.js
  test("404 page renders inside app shell with Header and Footer intact", async ({
    page,
  }) => {
    // Arrange + Act: navigate to a clearly invalid route
    await page.goto("/this-route-does-not-exist-xyz-404");

    // Assert – 404 page-specific content
    await expect(page.getByText("404")).toBeVisible({ timeout: 10000 });
    await expect(page.getByText("Oops ! Page Not Found")).toBeVisible();

    // Assert – "Go Back" link points back to home
    const goBackLink = page.getByRole("link", { name: "Go Back" });
    await expect(goBackLink).toBeVisible();
    await expect(goBackLink).toHaveAttribute("href", "/");

    // Assert – Header shell is intact around the 404 content
    await expect(page.getByRole("link", { name: BRAND })).toBeVisible();
    await expect(page.getByRole("link", { name: "Login" })).toBeVisible();

    // Assert – Footer shell is intact around the 404 content
    await expect(page.getByText(COPYRIGHT)).toBeVisible();
    await expect(
      page.locator(".footer").getByRole("link", { name: "About" })
    ).toBeVisible();
  });

  // ── Test 4 ──────────────────────────────────────────────────────────────────
  // Verifies that Spinner is shown for an unauthenticated access attempt on a
  // PrivateRoute, counts down, then redirects to "/" — and that the destination
  // page is still wrapped in the full shell.
  // Exercises: Private.js · Spinner.js · Layout.js · Header.js · Footer.js
  test("Spinner redirects unauthenticated user from protected route and destination page has shell", async ({
    page,
  }) => {
    // Arrange: no prior login — Playwright context has empty localStorage

    // Act: navigate directly to a PrivateRoute-protected URL
    await page.goto("/dashboard/user");

    // Assert – Spinner countdown is immediately visible
    // (PrivateRoute detects no token and renders Spinner, not the page content)
    await expect(
      page.getByText(/redirecting to you in/i)
    ).toBeVisible({ timeout: 5000 });

    // Assert – spinner-border element (Bootstrap spinner) is visible
    await expect(page.locator(".spinner-border")).toBeVisible();

    // Act + Assert – Spinner counts to 0 then navigates to "/" (path="" on
    // PrivateRoute); wait up to 8 s to allow the 3-second countdown to finish
    await expect(page).toHaveURL("http://localhost:3000/", { timeout: 8000 });

    // Assert – the redirect destination is wrapped in the full Layout shell
    await expect(page.getByRole("link", { name: BRAND })).toBeVisible();
    await expect(page.getByText(COPYRIGHT)).toBeVisible();
    await expect(
      page.getByRole("heading", { name: "All Products" })
    ).toBeVisible({ timeout: 10000 });
  });

  // ── Test 5 ──────────────────────────────────────────────────────────────────
  // Verifies that clicking "Go Back" on the 404 page returns the user to the
  // Home page, and the full shell is still intact throughout.
  // Exercises: Pagenotfound.js · Header.js · Footer.js · HomePage.js
  test("Go Back link on 404 page returns to Home page with shell intact", async ({
    page,
  }) => {
    // Arrange: land on the 404 page
    await page.goto("/non-existent-page-abc");
    await expect(page.getByText("404")).toBeVisible({ timeout: 10000 });

    // Act: click the "Go Back" link
    await page.getByRole("link", { name: "Go Back" }).click();

    // Assert – redirected back to home
    await expect(page).toHaveURL("http://localhost:3000/");

    // Assert – Home page content rendered
    await expect(
      page.getByRole("heading", { name: "All Products" })
    ).toBeVisible({ timeout: 10000 });

    // Assert – shell fully intact on the home page
    await expect(page.getByRole("link", { name: BRAND })).toBeVisible();
    await expect(page.getByText(COPYRIGHT)).toBeVisible();
  });
});
