import { test, expect } from "@playwright/test";

// Zhu Shiqi, A0271719X
// Generated by Claude Code, Sonnet 4.6
const VALID_EMAIL = "cs4218@test.com";
const VALID_PASSWORD = "cs4218@test.com";
const VALID_NAME = "CS 4218 Test Account";

async function loginWithValidAccount(page) {
  await page.goto("/login");
  await page.locator("#exampleInputEmail1").fill(VALID_EMAIL);
  await page.locator("#exampleInputPassword1").fill(VALID_PASSWORD);
  await page.getByRole("button", { name: "LOGIN" }).click();
  await expect(page).toHaveURL("http://localhost:3000/");
}

async function registerNewUser(page) {
  const timestamp = Date.now();
  const userData = {
    name: `Test User ${timestamp}`,
    email: `testuser${timestamp}@example.com`,
    password: "TestPassword123",
    phone: "91234567",
    address: "123 Test Street",
    answer: "Soccer",
    dob: "2000-01-01",
  };

  await page.goto("/register");
  await page.locator("#exampleInputName1").fill(userData.name);
  await page.locator("#exampleInputEmail1").fill(userData.email);
  await page.locator("#exampleInputPassword1").fill(userData.password);
  await page.locator("#exampleInputPhone1").fill(userData.phone);
  await page.locator("#exampleInputaddress1").fill(userData.address);
  await page.locator("#exampleInputDOB1").fill(userData.dob);
  await page.locator("#exampleInputanswer1").fill(userData.answer);
  await page.getByRole("button", { name: "REGISTER" }).click();

  return userData;
}

// UI Tests for Login

test("login with valid credentials redirects to home and shows user name in navbar", async ({
  page,
}) => {
  await page.goto("/login");

  await page.locator("#exampleInputEmail1").fill(VALID_EMAIL);
  await page.locator("#exampleInputPassword1").fill(VALID_PASSWORD);
  await page.getByRole("button", { name: "LOGIN" }).click();

  await expect(page).toHaveURL("http://localhost:3000/");
  await expect(page.locator(".navbar")).toContainText(VALID_NAME);
});

test("login with wrong password shows Invalid Password error", async ({
  page,
}) => {
  await page.goto("/login");

  await page.locator("#exampleInputEmail1").fill(VALID_EMAIL);
  await page.locator("#exampleInputPassword1").fill("wrongpassword");
  await page.getByRole("button", { name: "LOGIN" }).click();

  await expect(page.getByText("Invalid Password")).toBeVisible({ timeout: 5000 });
  await expect(page).toHaveURL(/\/login/);
});

test("login with unregistered email shows Something went wrong error", async ({
  page,
}) => {
  await page.goto("/login");

  await page.locator("#exampleInputEmail1").fill("notregistered@example.com");
  await page.locator("#exampleInputPassword1").fill("somepassword");
  await page.getByRole("button", { name: "LOGIN" }).click();

  await expect(page.getByText("Something went wrong")).toBeVisible({ timeout: 5000 });
  await expect(page).toHaveURL(/\/login/);
});

test("login then navigate to user dashboard displays name and email", async ({
  page,
}) => {
  await loginWithValidAccount(page);
  await page.goto("/dashboard/user");

  await expect(page.locator(".card")).toContainText(VALID_NAME);
  await expect(page.locator(".card")).toContainText(VALID_EMAIL);
});

test("Forgot Password button navigates to forgot-password page", async ({
  page,
}) => {
  await page.goto("/login");
  await page.getByRole("button", { name: "Forgot Password" }).click();

  await expect(page).toHaveURL(/\/forgot-password/);
});

// UI Tests for Registration

test("full registration flow then login with new account", async ({
  page,
}) => {
  const userData = await registerNewUser(page);

  await expect(page.getByText("Register Successfully, please login")).toBeVisible({
    timeout: 5000,
  });
  await expect(page).toHaveURL(/\/login/);

  await page.locator("#exampleInputEmail1").fill(userData.email);
  await page.locator("#exampleInputPassword1").fill(userData.password);
  await page.getByRole("button", { name: "LOGIN" }).click();

  await expect(page).toHaveURL("http://localhost:3000/");
  await expect(page.locator(".navbar")).toContainText(userData.name);
});

test("duplicate email registration shows Already Register error", async ({
  page,
}) => {
  await page.goto("/register");
  await page.locator("#exampleInputName1").fill("Duplicate User");
  await page.locator("#exampleInputEmail1").fill(VALID_EMAIL);
  await page.locator("#exampleInputPassword1").fill("somepassword");
  await page.locator("#exampleInputPhone1").fill("91234567");
  await page.locator("#exampleInputaddress1").fill("Some Address");
  await page.locator("#exampleInputDOB1").fill("2000-01-01");
  await page.locator("#exampleInputanswer1").fill("Soccer");
  await page.getByRole("button", { name: "REGISTER" }).click();

  await expect(page.getByText("Already Register please login")).toBeVisible({
    timeout: 5000,
  });
  await expect(page).toHaveURL(/\/register/);
});

test("registration then view profile reflects submitted data", async ({
  page,
}) => {
  const userData = await registerNewUser(page);
  await expect(page).toHaveURL(/\/login/);

  await page.locator("#exampleInputEmail1").fill(userData.email);
  await page.locator("#exampleInputPassword1").fill(userData.password);
  await page.getByRole("button", { name: "LOGIN" }).click();
  await expect(page).toHaveURL("http://localhost:3000/");

  await page.goto("/dashboard/user/profile");

  await expect(page.locator('input[placeholder="Enter Your Name"]')).toHaveValue(userData.name);
  await expect(page.locator('input[placeholder="Enter Your Email "]')).toHaveValue(userData.email);
  await expect(page.locator('input[placeholder="Enter Your Phone"]')).toHaveValue(userData.phone);
  await expect(page.locator('input[placeholder="Enter Your Address"]')).toHaveValue(userData.address);
});