import { test, expect } from "@playwright/test";
import {
  USER_EMAIL,
  USER_PASSWORD,
  USER_NAME,
  USER_ADDRESS,
  ADMIN_EMAIL,
  ADMIN_PASSWORD,
  ADMIN_NAME,
  ADMIN_PHONE,
  PRODUCT_SLUG,
  PRODUCT_NAME,
} from "./global-setup.js";

// Jinhan Wu
// Generated by Claude Code, Sonnet 4.6
//
// End-to-end tests for the authentication flow.
// Database seeding is handled by global-setup.js which starts a
// MongoMemoryServer before the app server, so no real MongoDB is required.

// ── Login helpers ─────────────────────────────────────────────────────────────

async function loginAsUser(page) {
  await page.goto("/login");
  await page.locator("#exampleInputEmail1").fill(USER_EMAIL);
  await page.locator("#exampleInputPassword1").fill(USER_PASSWORD);
  await page.getByRole("button", { name: "LOGIN" }).click();
  await expect(page).toHaveURL("http://localhost:3000/");
}

async function loginAsAdmin(page) {
  await page.goto("/login");
  await page.locator("#exampleInputEmail1").fill(ADMIN_EMAIL);
  await page.locator("#exampleInputPassword1").fill(ADMIN_PASSWORD);
  await page.getByRole("button", { name: "LOGIN" }).click();
  await expect(page).toHaveURL("http://localhost:3000/");
}

// ─────────────────────────────────────────────────────────────────────────────

test.describe("Auth flow end-to-end", () => {
  // No beforeAll needed — global-setup.js seeds all data before the server starts.

  // ── Scenario 1 ───────────────────────────────────────────────────────────────
  // Login → PrivateRoute allows access → user dashboard shows user-specific data.
  // Spans: Login.js → context/auth.js → Private.js (calls /api/v1/auth/user-auth)
  //        → Dashboard.js
  test("Scenario 1: Login then user dashboard displays name, email and address", async ({
    page,
  }) => {
    // Arrange: log in as the seeded regular user
    await loginAsUser(page);

    // Act: navigate directly to the PrivateRoute-protected user dashboard
    await page.goto("/dashboard/user");

    // Assert: route was not blocked and the user's personal data is rendered
    await expect(page).toHaveURL("http://localhost:3000/dashboard/user");
    const card = page.locator(".card").first();
    await expect(card).toContainText(USER_NAME);
    await expect(card).toContainText(USER_EMAIL);
    await expect(card).toContainText(USER_ADDRESS);
  });

  // ── Scenario 2 ───────────────────────────────────────────────────────────────
  // Login → navigate to product detail page → add to cart → cart shows the item
  // and personalised greeting (auth-aware CartPage).
  // Spans: Login.js → ProductDetails.js (Add To Cart) → context/cart.js
  //        → CartPage.js
  test("Scenario 2: Login then add product to cart then cart shows item and personalised greeting", async ({
    page,
  }) => {
    // Arrange: log in and open the seeded product's detail page
    await loginAsUser(page);
    await page.goto(`/product/${PRODUCT_SLUG}`);

    // Act: wait for product details to load and add it to the cart
    await expect(
      page.getByText(`Name: ${PRODUCT_NAME}`)
    ).toBeVisible({ timeout: 10000 });
    await page.getByRole("button", { name: "Add To Cart" }).click();

    // Navigate to the cart page
    await page.goto("/cart");

    // Assert: CartPage personalised greeting ("Hello  <name>" — two spaces by design)
    await expect(page.getByText(`Hello  ${USER_NAME}`)).toBeVisible();
    // Assert: item count reflects the single product we added
    await expect(
      page.getByText("You Have 1 items in your cart")
    ).toBeVisible();
    // Assert: product name is listed in the cart item row
    await expect(page.getByText(PRODUCT_NAME)).toBeVisible();
  });

  // ── Scenario 3 ───────────────────────────────────────────────────────────────
  // Guest (unauthenticated) adds a product to the cart.
  // CartPage detects no auth token and prompts the user to log in, while still
  // showing the item — auth-context is read correctly by CartPage.
  // Spans: ProductDetails.js (Add To Cart) → context/cart.js → CartPage.js
  test("Scenario 3: Guest adds product to cart then cart prompts login to checkout", async ({
    page,
  }) => {
    // Arrange: no login — fresh Playwright context has empty localStorage
    await page.goto(`/product/${PRODUCT_SLUG}`);
    await expect(
      page.getByText(`Name: ${PRODUCT_NAME}`)
    ).toBeVisible({ timeout: 10000 });

    // Act: add the item as a guest
    await page.getByRole("button", { name: "Add To Cart" }).click();
    await page.goto("/cart");

    // Assert: guest greeting (no personalised name)
    await expect(page.getByText("Hello Guest")).toBeVisible();
    // Assert: login prompt is shown alongside the item count
    await expect(
      page.getByText("Please login to checkout !")
    ).toBeVisible();
    // Assert: product is still displayed in the cart
    await expect(page.getByText(PRODUCT_NAME)).toBeVisible();
  });

  // ── Scenario 4 ───────────────────────────────────────────────────────────────
  // Login → access protected page → logout via navbar → session is cleared →
  // revisiting the protected route triggers PrivateRoute/Spinner redirect.
  // Spans: Login.js → Dashboard.js → Header.js (handleLogout) → context/auth.js
  //        → Private.js → Spinner.js
  test("Scenario 4: Logout clears session and protected route redirects to home", async ({
    page,
  }) => {
    // Arrange: log in and verify the protected dashboard is reachable
    await loginAsUser(page);
    await page.goto("/dashboard/user");
    await expect(page).toHaveURL("http://localhost:3000/dashboard/user");

    // Act: open the navbar user dropdown (Bootstrap 5) and click Logout
    await page.locator(".navbar").getByText(USER_NAME).click();
    await expect(
      page.getByRole("link", { name: "Logout" })
    ).toBeVisible({ timeout: 5000 });
    await page.getByRole("link", { name: "Logout" }).click();

    // Assert: redirected to /login after logout
    await expect(page).toHaveURL(/\/login/);
    // Assert: navbar now shows anonymous links (Login/Register)
    await expect(page.getByRole("link", { name: "Login" })).toBeVisible();

    // Act: attempt to access the protected dashboard without a session
    await page.goto("/dashboard/user");

    // Assert: PrivateRoute shows Spinner (path="") which redirects to "/" after 3 s
    await expect(page).toHaveURL("http://localhost:3000/", { timeout: 8000 });
  });

  // ── Scenario 5 ───────────────────────────────────────────────────────────────
  // Admin login → AdminRoute allows access → admin dashboard shows admin data.
  // Spans: Login.js → context/auth.js → AdminRoute.js (calls /api/v1/auth/admin-auth)
  //        → AdminDashboard.js
  test("Scenario 5: Admin login then admin dashboard displays admin-specific information", async ({
    page,
  }) => {
    // Arrange: log in as the seeded admin user
    await loginAsAdmin(page);

    // Act: navigate to the AdminRoute-protected admin dashboard
    await page.goto("/dashboard/admin");

    // Assert: route was not blocked and admin data is rendered
    await expect(page).toHaveURL("http://localhost:3000/dashboard/admin");
    await expect(
      page.getByText(`Admin Name : ${ADMIN_NAME}`)
    ).toBeVisible({ timeout: 10000 });
    await expect(
      page.getByText(`Admin Email : ${ADMIN_EMAIL}`)
    ).toBeVisible();
    await expect(
      page.getByText(`Admin Contact : ${ADMIN_PHONE}`)
    ).toBeVisible();
  });
});
