import { test, expect } from "@playwright/test";
import dotenv from "dotenv";
import mongoose from "mongoose";
import userModel from "../../models/userModel.js";
import categoryModel from "../../models/categoryModel.js";
import productModel from "../../models/productModel.js";
import { hashPassword } from "../../helpers/authHelper.js";

dotenv.config();

// Jinhan Wu
// Generated by Claude Code, Sonnet 4.6
//
// End-to-end tests for the authentication flow.
// Requires MONGO_URL to be set in the environment (GitHub Actions secret).

// ── Credentials ───────────────────────────────────────────────────────────────

const USER_EMAIL = "e2e-auth-flow-user@example.com";
const USER_PASSWORD = "AuthFlow123!";
const USER_NAME = "E2E Auth Flow User";
const USER_ADDRESS = "456 Auth Flow Street";
const USER_PHONE = "91234567";

const ADMIN_EMAIL = "e2e-admin@example.com";
const ADMIN_PASSWORD = "AdminFlow123!";
const ADMIN_NAME = "E2E Auth Admin";
const ADMIN_PHONE = "91234567";

const CATEGORY_SLUG = "e2e-auth-flow-cat";
const CATEGORY_NAME = "E2E Auth Flow Category";
const PRODUCT_SLUG = "e2e-auth-flow-product";
const PRODUCT_NAME = "E2E Auth Flow Product";
const PRODUCT_DESCRIPTION = "Test product used by E2E auth flow tests";
const PRODUCT_PRICE = 49;

// ── Database seed ─────────────────────────────────────────────────────────────

async function seedAll() {
  if (!process.env.MONGO_URL) {
    throw new Error("MONGO_URL is required to seed auth-flow E2E data");
  }

  await mongoose.connect(process.env.MONGO_URL);

  try {
    const hashedUserPw = await hashPassword(USER_PASSWORD);
    await userModel.findOneAndUpdate(
      { email: USER_EMAIL },
      {
        name: USER_NAME,
        email: USER_EMAIL,
        password: hashedUserPw,
        phone: USER_PHONE,
        address: USER_ADDRESS,
        answer: "Soccer",
        role: 0,
      },
      { upsert: true, new: true, setDefaultsOnInsert: true }
    );

    const hashedAdminPw = await hashPassword(ADMIN_PASSWORD);
    await userModel.findOneAndUpdate(
      { email: ADMIN_EMAIL },
      {
        name: ADMIN_NAME,
        email: ADMIN_EMAIL,
        password: hashedAdminPw,
        phone: ADMIN_PHONE,
        address: "123 Admin Street",
        answer: "Soccer",
        role: 1,
      },
      { upsert: true, new: true, setDefaultsOnInsert: true }
    );

    const category = await categoryModel.findOneAndUpdate(
      { slug: CATEGORY_SLUG },
      { name: CATEGORY_NAME, slug: CATEGORY_SLUG },
      { upsert: true, new: true, setDefaultsOnInsert: true }
    );

    const tinyPng = Buffer.from(
      "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO2Z8x8AAAAASUVORK5CYII=",
      "base64"
    );

    await productModel.findOneAndUpdate(
      { slug: PRODUCT_SLUG },
      {
        name: PRODUCT_NAME,
        slug: PRODUCT_SLUG,
        description: PRODUCT_DESCRIPTION,
        price: PRODUCT_PRICE,
        category: category._id,
        quantity: 5,
        shipping: true,
        photo: { data: tinyPng, contentType: "image/png" },
      },
      { upsert: true, new: true, setDefaultsOnInsert: true }
    );
  } finally {
    await mongoose.disconnect();
  }
}

// ── Login helpers ─────────────────────────────────────────────────────────────

async function loginAsUser(page) {
  await page.goto("/login");
  await page.locator("#exampleInputEmail1").fill(USER_EMAIL);
  await page.locator("#exampleInputPassword1").fill(USER_PASSWORD);
  await page.getByRole("button", { name: "LOGIN" }).click();
  await expect(page).toHaveURL("http://localhost:3000/");
}

async function loginAsAdmin(page) {
  await page.goto("/login");
  await page.locator("#exampleInputEmail1").fill(ADMIN_EMAIL);
  await page.locator("#exampleInputPassword1").fill(ADMIN_PASSWORD);
  await page.getByRole("button", { name: "LOGIN" }).click();
  await expect(page).toHaveURL("http://localhost:3000/");
}

// ─────────────────────────────────────────────────────────────────────────────

test.describe("Auth flow end-to-end", () => {
  test.beforeAll(async () => {
    await seedAll();
  });

  // ── Scenario 1 ───────────────────────────────────────────────────────────────
  test("Scenario 1: Login then user dashboard displays name, email and address", async ({
    page,
  }) => {
    await loginAsUser(page);
    await page.goto("/dashboard/user");

    await expect(page).toHaveURL("http://localhost:3000/dashboard/user");
    const card = page.locator(".card").first();
    await expect(card).toContainText(USER_NAME);
    await expect(card).toContainText(USER_EMAIL);
    await expect(card).toContainText(USER_ADDRESS);
  });

  // ── Scenario 2 ───────────────────────────────────────────────────────────────
  test("Scenario 2: Login then add product to cart then cart shows item and personalised greeting", async ({
    page,
  }) => {
    await loginAsUser(page);
    await page.goto(`/product/${PRODUCT_SLUG}`);

    await expect(
      page.getByText(`Name: ${PRODUCT_NAME}`)
    ).toBeVisible({ timeout: 10000 });
    await page.getByRole("button", { name: "Add To Cart" }).click();
    await page.goto("/cart");

    await expect(page.getByText(`Hello  ${USER_NAME}`)).toBeVisible();
    await expect(page.getByText("You Have 1 items in your cart")).toBeVisible();
    await expect(page.getByText(PRODUCT_NAME)).toBeVisible();
  });

  // ── Scenario 3 ───────────────────────────────────────────────────────────────
  test("Scenario 3: Guest adds product to cart then cart prompts login to checkout", async ({
    page,
  }) => {
    await page.goto(`/product/${PRODUCT_SLUG}`);
    await expect(
      page.getByText(`Name: ${PRODUCT_NAME}`)
    ).toBeVisible({ timeout: 10000 });

    await page.getByRole("button", { name: "Add To Cart" }).click();
    await page.goto("/cart");

    await expect(page.getByText("Hello Guest")).toBeVisible();
    await expect(page.getByText("Please login to checkout !")).toBeVisible();
    await expect(page.getByText(PRODUCT_NAME)).toBeVisible();
  });

  // ── Scenario 4 ───────────────────────────────────────────────────────────────
  test("Scenario 4: Logout clears session and protected route redirects to home", async ({
    page,
  }) => {
    await loginAsUser(page);
    await page.goto("/dashboard/user");
    await expect(page).toHaveURL("http://localhost:3000/dashboard/user");

    await page.locator(".navbar").getByText(USER_NAME).click();
    await expect(
      page.getByRole("link", { name: "Logout" })
    ).toBeVisible({ timeout: 5000 });
    await page.getByRole("link", { name: "Logout" }).click();

    await expect(page).toHaveURL(/\/login/);
    await expect(page.getByRole("link", { name: "Login" })).toBeVisible();

    await page.goto("/dashboard/user");
    await expect(page).toHaveURL("http://localhost:3000/", { timeout: 8000 });
  });

  // ── Scenario 5 ───────────────────────────────────────────────────────────────
  test("Scenario 5: Admin login then admin dashboard displays admin-specific information", async ({
    page,
  }) => {
    await loginAsAdmin(page);
    await page.goto("/dashboard/admin");

    await expect(page).toHaveURL("http://localhost:3000/dashboard/admin");
    await expect(
      page.getByText(`Admin Name : ${ADMIN_NAME}`)
    ).toBeVisible({ timeout: 10000 });
    await expect(page.getByText(`Admin Email : ${ADMIN_EMAIL}`)).toBeVisible();
    await expect(page.getByText(`Admin Contact : ${ADMIN_PHONE}`)).toBeVisible();
  });
});
