import { test, expect } from "@playwright/test";
import dotenv from "dotenv";
import mongoose from "mongoose";
import userModel from "../../models/userModel.js";
import categoryModel from "../../models/categoryModel.js";
import productModel from "../../models/productModel.js";
import { hashPassword } from "../../helpers/authHelper.js";

dotenv.config();

// Jinhan Wu
// Generated by Claude Code, Sonnet 4.6

// ── Regular user credentials ──────────────────────────────────────────────────
const USER_EMAIL = "e2e-auth-flow-user@example.com";
const USER_PASSWORD = "AuthFlow123!";
const USER_NAME = "E2E Auth Flow User";
const USER_ADDRESS = "456 Auth Flow Street";
const USER_PHONE = "91234567";

// ── Admin credentials ─────────────────────────────────────────────────────────
const ADMIN_EMAIL = process.env.ADMIN_EMAIL || "admin@admin.com";
const ADMIN_PASSWORD = process.env.ADMIN_PASSWORD || "admin";
const ADMIN_NAME = "E2E Auth Admin";
const ADMIN_PHONE = "91234567";

// ── Seeded product constants ──────────────────────────────────────────────────
const CATEGORY_SLUG = "e2e-auth-flow-cat";
const CATEGORY_NAME = "E2E Auth Flow Category";
const PRODUCT_SLUG = "e2e-auth-flow-product";
const PRODUCT_NAME = "E2E Auth Flow Product";
const PRODUCT_DESCRIPTION = "Test product used by E2E auth flow tests";
const PRODUCT_PRICE = 49;

// ── Database seed ─────────────────────────────────────────────────────────────

async function seedAll() {
  if (!process.env.MONGO_URL) {
    throw new Error("MONGO_URL is required to seed auth-flow E2E data");
  }

  await mongoose.connect(process.env.MONGO_URL);

  try {
    // Regular user
    const hashedUserPw = await hashPassword(USER_PASSWORD);
    await userModel.findOneAndUpdate(
      { email: USER_EMAIL },
      {
        name: USER_NAME,
        email: USER_EMAIL,
        password: hashedUserPw,
        phone: USER_PHONE,
        address: USER_ADDRESS,
        answer: "Soccer",
        role: 0,
      },
      { upsert: true, new: true, setDefaultsOnInsert: true }
    );

    // Admin user
    const hashedAdminPw = await hashPassword(ADMIN_PASSWORD);
    await userModel.findOneAndUpdate(
      { email: ADMIN_EMAIL },
      {
        name: ADMIN_NAME,
        email: ADMIN_EMAIL,
        password: hashedAdminPw,
        phone: ADMIN_PHONE,
        address: "123 Admin Street",
        answer: "Soccer",
        role: 1,
      },
      { upsert: true, new: true, setDefaultsOnInsert: true }
    );

    // Category required by the test product
    const category = await categoryModel.findOneAndUpdate(
      { slug: CATEGORY_SLUG },
      { name: CATEGORY_NAME, slug: CATEGORY_SLUG },
      { upsert: true, new: true, setDefaultsOnInsert: true }
    );

    // Minimal 1×1 PNG so the product-photo endpoint does not 500
    const tinyPng = Buffer.from(
      "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO2Z8x8AAAAASUVORK5CYII=",
      "base64"
    );

    await productModel.findOneAndUpdate(
      { slug: PRODUCT_SLUG },
      {
        name: PRODUCT_NAME,
        slug: PRODUCT_SLUG,
        description: PRODUCT_DESCRIPTION,
        price: PRODUCT_PRICE,
        category: category._id,
        quantity: 5,
        shipping: true,
        photo: { data: tinyPng, contentType: "image/png" },
      },
      { upsert: true, new: true, setDefaultsOnInsert: true }
    );
  } finally {
    await mongoose.disconnect();
  }
}

// ── Login helpers ─────────────────────────────────────────────────────────────

async function loginAsUser(page) {
  await page.goto("/login");
  await page.locator("#exampleInputEmail1").fill(USER_EMAIL);
  await page.locator("#exampleInputPassword1").fill(USER_PASSWORD);
  await page.getByRole("button", { name: "LOGIN" }).click();
  await expect(page).toHaveURL("http://localhost:3000/");
}

async function loginAsAdmin(page) {
  await page.goto("/login");
  await page.locator("#exampleInputEmail1").fill(ADMIN_EMAIL);
  await page.locator("#exampleInputPassword1").fill(ADMIN_PASSWORD);
  await page.getByRole("button", { name: "LOGIN" }).click();
  await expect(page).toHaveURL("http://localhost:3000/");
}

// ─────────────────────────────────────────────────────────────────────────────

test.describe("Auth flow end-to-end", () => {
  test.beforeAll(async () => {
    await seedAll();
  });

  // ── Scenario 1 ───────────────────────────────────────────────────────────────
  // Login → PrivateRoute allows access → user dashboard shows user-specific data.
  // Spans: Login.js → context/auth.js → Private.js (calls /api/v1/auth/user-auth)
  //        → Dashboard.js
  test("Scenario 1: Login then user dashboard displays name, email and address", async ({
    page,
  }) => {
    // Arrange: log in as the seeded regular user
    await loginAsUser(page);

    // Act: navigate directly to the PrivateRoute-protected user dashboard
    await page.goto("/dashboard/user");

    // Assert: route was not blocked and the user's personal data is rendered
    await expect(page).toHaveURL("http://localhost:3000/dashboard/user");
    const card = page.locator(".card").first();
    await expect(card).toContainText(USER_NAME);
    await expect(card).toContainText(USER_EMAIL);
    await expect(card).toContainText(USER_ADDRESS);
  });

  // ── Scenario 2 ───────────────────────────────────────────────────────────────
  // Login → navigate to product detail page → add to cart → cart shows the item
  // and personalised greeting (auth-aware CartPage).
  // Spans: Login.js → ProductDetails.js (Add To Cart) → context/cart.js
  //        → CartPage.js
  test("Scenario 2: Login then add product to cart then cart shows item and personalised greeting", async ({
    page,
  }) => {
    // Arrange: log in and open the seeded product's detail page
    await loginAsUser(page);
    await page.goto(`/product/${PRODUCT_SLUG}`);

    // Act: wait for product details to load and add it to the cart
    await expect(
      page.getByText(`Name: ${PRODUCT_NAME}`)
    ).toBeVisible({ timeout: 10000 });
    await page.getByRole("button", { name: "Add To Cart" }).click();

    // Navigate to the cart page
    await page.goto("/cart");

    // Assert: CartPage personalised greeting ("Hello  <name>" — two spaces by design)
    await expect(page.getByText(`Hello  ${USER_NAME}`)).toBeVisible();
    // Assert: item count reflects the single product we added
    await expect(
      page.getByText("You Have 1 items in your cart")
    ).toBeVisible();
    // Assert: product name is listed in the cart item row
    await expect(page.getByText(PRODUCT_NAME)).toBeVisible();
  });

  // ── Scenario 3 ───────────────────────────────────────────────────────────────
  // Guest (unauthenticated) adds a product to the cart.
  // CartPage detects no auth token and prompts the user to log in, while still
  // showing the item — auth-context is read correctly by CartPage.
  // Spans: ProductDetails.js (Add To Cart) → context/cart.js → CartPage.js
  test("Scenario 3: Guest adds product to cart then cart prompts login to checkout", async ({
    page,
  }) => {
    // Arrange: no login — fresh Playwright context has empty localStorage
    await page.goto(`/product/${PRODUCT_SLUG}`);
    await expect(
      page.getByText(`Name: ${PRODUCT_NAME}`)
    ).toBeVisible({ timeout: 10000 });

    // Act: add the item as a guest
    await page.getByRole("button", { name: "Add To Cart" }).click();
    await page.goto("/cart");

    // Assert: guest greeting (no personalised name)
    await expect(page.getByText("Hello Guest")).toBeVisible();
    // Assert: login prompt is shown alongside the item count
    await expect(
      page.getByText("Please login to checkout !")
    ).toBeVisible();
    // Assert: product is still displayed in the cart
    await expect(page.getByText(PRODUCT_NAME)).toBeVisible();
  });

  // ── Scenario 4 ───────────────────────────────────────────────────────────────
  // Login → access protected page → logout via navbar → session is cleared →
  // revisiting the protected route triggers PrivateRoute/Spinner redirect.
  // Spans: Login.js → Dashboard.js → Header.js (handleLogout) → context/auth.js
  //        → Private.js → Spinner.js
  test("Scenario 4: Logout clears session and protected route redirects to home", async ({
    page,
  }) => {
    // Arrange: log in and verify the protected dashboard is reachable
    await loginAsUser(page);
    await page.goto("/dashboard/user");
    await expect(page).toHaveURL("http://localhost:3000/dashboard/user");

    // Act: open the navbar user dropdown (Bootstrap 5) and click Logout
    await page.locator(".navbar").getByText(USER_NAME).click();
    await expect(
      page.getByRole("link", { name: "Logout" })
    ).toBeVisible({ timeout: 5000 });
    await page.getByRole("link", { name: "Logout" }).click();

    // Assert: redirected to /login after logout
    await expect(page).toHaveURL(/\/login/);
    // Assert: navbar now shows anonymous links (Login/Register)
    await expect(page.getByRole("link", { name: "Login" })).toBeVisible();

    // Act: attempt to access the protected dashboard without a session
    await page.goto("/dashboard/user");

    // Assert: PrivateRoute shows Spinner (path="") which redirects to "/" after 3 s
    await expect(page).toHaveURL("http://localhost:3000/", { timeout: 8000 });
  });

  // ── Scenario 5 ───────────────────────────────────────────────────────────────
  // Admin login → AdminRoute allows access → admin dashboard shows admin data.
  // Spans: Login.js → context/auth.js → AdminRoute.js (calls /api/v1/auth/admin-auth)
  //        → AdminDashboard.js
  test("Scenario 5: Admin login then admin dashboard displays admin-specific information", async ({
    page,
  }) => {
    // Arrange: log in as the seeded admin user
    await loginAsAdmin(page);

    // Act: navigate to the AdminRoute-protected admin dashboard
    await page.goto("/dashboard/admin");

    // Assert: route was not blocked and admin data is rendered
    await expect(page).toHaveURL("http://localhost:3000/dashboard/admin");
    await expect(
      page.getByText(`Admin Name : ${ADMIN_NAME}`)
    ).toBeVisible({ timeout: 10000 });
    await expect(
      page.getByText(`Admin Email : ${ADMIN_EMAIL}`)
    ).toBeVisible();
    await expect(
      page.getByText(`Admin Contact : ${ADMIN_PHONE}`)
    ).toBeVisible();
  });
});
