import { test, expect } from "@playwright/test";
import dotenv from "dotenv";
import mongoose from "mongoose";
import categoryModel from "../../models/categoryModel.js";
import productModel from "../../models/productModel.js";

dotenv.config();

// Zhu Shiqi, A0271719X
// Generated by Claude Code, Sonnet 4.6
const MATCHING_KEYWORD = "a";
const NO_MATCH_KEYWORD = "xyznonexistentproduct99999";

const SEEDED_CATEGORY_SLUG = "e2e-search-category";
const SEEDED_PRODUCT_SLUG = "e2e-search-product-alpha";

async function seedData() {
  if (!process.env.MONGO_URL) {
    throw new Error("MONGO_URL is required to seed E2E search data");
  }

  await mongoose.connect(process.env.MONGO_URL);

  try {
    const category = await categoryModel.findOneAndUpdate(
      { slug: SEEDED_CATEGORY_SLUG },
      { name: "E2E Search Category", slug: SEEDED_CATEGORY_SLUG },
      { upsert: true, new: true, setDefaultsOnInsert: true }
    );

    await productModel.findOneAndUpdate(
      { slug: SEEDED_PRODUCT_SLUG },
      {
        name: "Alpha Test Product",
        slug: SEEDED_PRODUCT_SLUG,
        description: "This is a searchable product description for e2e tests",
        price: 99,
        category: category._id,
        quantity: 10,
        shipping: true,
      },
      { upsert: true, new: true, setDefaultsOnInsert: true }
    );
  } finally {
    await mongoose.disconnect();
  }
}

async function cleanupData() {
  if (!process.env.MONGO_URL) return;

  await mongoose.connect(process.env.MONGO_URL);
  try {
    await productModel.deleteOne({ slug: SEEDED_PRODUCT_SLUG });
    await categoryModel.deleteOne({ slug: SEEDED_CATEGORY_SLUG });
  } finally {
    await mongoose.disconnect();
  }
}

async function searchFor(page, keyword) {
  await page.locator('input[type="search"]').fill(keyword);
  await page.getByRole("button", { name: "Search" }).click();
}

// UI Tests for Search

test.beforeAll(async () => {
  await seedData();
});

test.afterAll(async () => {
  await cleanupData();
});

test("searching for a keyword navigates to the search results page", async ({
  page,
}) => {
  await page.goto("/");

  await searchFor(page, MATCHING_KEYWORD);

  await expect(page).toHaveURL(/\/search/);
  await expect(page.getByRole("heading", { name: "Search Results" })).toBeVisible();
});

test("searching with an unmatched keyword shows No Products Found", async ({
  page,
}) => {
  await page.goto("/");

  await searchFor(page, NO_MATCH_KEYWORD);

  await expect(page).toHaveURL(/\/search/);
  await expect(page.getByText("No Products Found")).toBeVisible();
});

test("search results page displays a found count when products match", async ({
  page,
}) => {
  await page.goto("/");

  await searchFor(page, MATCHING_KEYWORD);

  await expect(page).toHaveURL(/\/search/);
  await expect(page.getByText(/Found \d+/)).toBeVisible();
});

test("each product card shows name, truncated description, and price", async ({
  page,
}) => {
  await page.goto("/");

  await searchFor(page, MATCHING_KEYWORD);

  await expect(page).toHaveURL(/\/search/);

  const firstCard = page.locator(".card").first();
  await expect(firstCard.locator(".card-title")).toBeVisible();

  // Description is truncated to 30 chars then "..." appended
  const descriptionText = await firstCard.locator(".card-text").first().textContent();
  expect(descriptionText).toMatch(/\.{3}$/);

  // Price contains a $ sign
  await expect(firstCard.getByText(/\$\s*\d+/)).toBeVisible();
});

test("each product card has More Details and ADD TO CART buttons", async ({
  page,
}) => {
  await page.goto("/");

  await searchFor(page, MATCHING_KEYWORD);

  await expect(page).toHaveURL(/\/search/);

  const firstCard = page.locator(".card").first();
  await expect(firstCard.getByRole("button", { name: "More Details" })).toBeVisible();
  await expect(firstCard.getByRole("button", { name: "ADD TO CART" })).toBeVisible();
});

test("performing a second search replaces the previous results", async ({
  page,
}) => {
  await page.goto("/");

  // First search — expect results
  await searchFor(page, MATCHING_KEYWORD);
  await expect(page).toHaveURL(/\/search/);
  await expect(page.getByText(/Found \d+/)).toBeVisible();

  // Second search — expect no results
  await searchFor(page, NO_MATCH_KEYWORD);
  await expect(page).toHaveURL(/\/search/);
  await expect(page.getByText("No Products Found")).toBeVisible();
});

test("search input retains the keyword after navigating to results page", async ({
  page,
}) => {
  await page.goto("/");

  await searchFor(page, MATCHING_KEYWORD);

  await expect(page).toHaveURL(/\/search/);
  await expect(page.locator('input[type="search"]')).toHaveValue(MATCHING_KEYWORD);
});

test("search is accessible from a non-home page", async ({
  page,
}) => {
  // Navigate to a different page
  await page.goto("/categories");

  await searchFor(page, MATCHING_KEYWORD);

  await expect(page).toHaveURL(/\/search/);
  await expect(page.getByRole("heading", { name: "Search Results" })).toBeVisible();
});

test("clicking More Details navigates to the product details page", async ({
  page,
}) => {
  await page.goto("/");

  await searchFor(page, MATCHING_KEYWORD);
  await expect(page).toHaveURL(/\/search/);

  const firstCard = page.locator(".card").first();
  const productName = await firstCard.locator(".card-title").textContent();

  await firstCard.getByRole("button", { name: "More Details" }).click();

  await expect(page).toHaveURL(/\/product\/.+/);
  await expect(page.getByRole("heading", { name: 'Name: ' + productName.trim()})).toBeVisible();
});

test("clicking ADD TO CART shows a success toast", async ({
  page,
}) => {
  await page.goto("/");

  await searchFor(page, MATCHING_KEYWORD);
  await expect(page).toHaveURL(/\/search/);

  const firstCard = page.locator(".card").first();
  await firstCard.getByRole("button", { name: "ADD TO CART" }).click();

  await expect(page.getByText("Item Added to cart")).toBeVisible();
});

test("search result count updates after new search", async ({
  page,
}) => {
  await page.goto("/");

  // First search — any matches
  await searchFor(page, MATCHING_KEYWORD);
  await expect(page).toHaveURL(/\/search/);

  const firstCountText = await page.locator("h6").textContent();

  // Second search — no matches, the message should differ
  await searchFor(page, NO_MATCH_KEYWORD);
  await expect(page).toHaveURL(/\/search/);
  // Wait for the new result to render before reading the text
  await expect(page.getByText("No Products Found")).toBeVisible();

  const secondCountText = await page.locator("h6").textContent();

  expect(firstCountText).not.toEqual(secondCountText);
  expect(secondCountText).toContain("No Products Found");
});
