import { test, expect } from "@playwright/test";
import dotenv from "dotenv";
import mongoose from "mongoose";
import userModel from "../../models/userModel.js";
import { hashPassword } from "../../helpers/authHelper.js";

dotenv.config();

// Zhu Shiqi, A0271719X
// Generated by Claude Code, Sonnet 4.6
const USER_EMAIL = "e2e-dashboard-user@example.com";
const USER_PASSWORD = "Dashboard123!";
const USER_NAME = "E2E Dashboard User";
const USER_ADDRESS = "123 Dashboard Street";

async function seedUser() {
  if (!process.env.MONGO_URL) {
    throw new Error("MONGO_URL is required to seed user dashboard E2E data");
  }

  await mongoose.connect(process.env.MONGO_URL);

  try {
    const hashed = await hashPassword(USER_PASSWORD);
    await userModel.findOneAndUpdate(
      { email: USER_EMAIL },
      {
        name: USER_NAME,
        email: USER_EMAIL,
        password: hashed,
        phone: "91234567",
        address: USER_ADDRESS,
        answer: "Soccer",
        role: 0,
      },
      { upsert: true, new: true, setDefaultsOnInsert: true }
    );
  } finally {
    await mongoose.disconnect();
  }
}

async function loginAsUser(page) {
  await page.goto("/login");
  await page.locator("#exampleInputEmail1").fill(USER_EMAIL);
  await page.locator("#exampleInputPassword1").fill(USER_PASSWORD);
  await page.getByRole("button", { name: "LOGIN" }).click();
  await expect(page).toHaveURL("http://localhost:3000/");
}

test.describe("user dashboard", () => {
  test.beforeAll(async () => {
    await seedUser();
  });

  test("Login then dashboard shows user info", async ({ page }) => {
    await loginAsUser(page);

    await page.goto("/dashboard/user");
    await expect(page).toHaveURL("http://localhost:3000/dashboard/user");

    await expect(page.getByRole("heading", { name: USER_NAME })).toBeVisible();
    await expect(page.getByRole("heading", { name: USER_EMAIL })).toBeVisible();
    await expect(page.getByRole("heading", { name: USER_ADDRESS })).toBeVisible();
  });

  test("Login then navigate to Profile via UserMenu", async ({ page }) => {
    await loginAsUser(page);

    await page.goto("/dashboard/user");
    await page.getByRole("link", { name: "Profile" }).click();

    await expect(page).toHaveURL("http://localhost:3000/dashboard/user/profile");
    await expect(page.getByRole("heading", { name: "USER PROFILE" })).toBeVisible();
    await expect(page.locator("input[placeholder='Enter Your Name']")).toBeVisible();
  });

  test("Login then update profile name", async ({ page }) => {
    await loginAsUser(page);

    await page.goto("/dashboard/user/profile");

    const updatedName = "E2E Updated Name";
    const nameInput = page.locator("input[placeholder='Enter Your Name']");
    await nameInput.clear();
    await nameInput.fill(updatedName);

    await page.getByRole("button", { name: "UPDATE", exact: true }).click();
    await expect(page.getByText("Profile Updated Successfully")).toBeVisible({ timeout: 10000 });

    await page.goto("/dashboard/user");
    await expect(page.getByRole("heading", { name: updatedName })).toBeVisible();

    // Restore original name
    await page.goto("/dashboard/user/profile");
    const nameInputRestore = page.locator("input[placeholder='Enter Your Name']");
    await nameInputRestore.clear();
    await nameInputRestore.fill(USER_NAME);
    await page.getByRole("button", { name: "UPDATE", exact: true }).click();
    await expect(page.getByText("Profile Updated Successfully")).toBeVisible({ timeout: 10000 });
  });

  test("Login then navigate to Orders via UserMenu", async ({ page }) => {
    await loginAsUser(page);

    await page.goto("/dashboard/user");
    await page.getByRole("link", { name: "Orders" }).click();

    await expect(page).toHaveURL("http://localhost:3000/dashboard/user/orders");
    await expect(page.getByRole("heading", { name: "All Orders" })).toBeVisible();
  });

  test("Unauthenticated access redirects", async ({ page }) => {
    await page.goto("/dashboard/user");

    await expect(page).not.toHaveURL("http://localhost:3000/dashboard/user");
  });
});
