/**
 * Zhu Shiqi, A0271719X
 * Generated by Claude Code
 * 
 * k6 Load Test — Shop page browsing flow
 *   Step 1: GET  /api/v1/product/product-count     (total for pagination)
 *   Step 2: GET  /api/v1/product/product-list/:page (fetch a results page)
 *   Step 3: POST /api/v1/product/product-filters    (apply price / category filter)
 *
 * Simulates the expected number of users browsing and filtering the shop
 * during normal peak periods.  Measures per-step and end-to-end response
 * times and throughput. 
 *
 * This models the journey a user takes immediately before checkout:
 * land on the shop → paginate → narrow results by filter → pick a product.
 */

import http from "k6/http";
import { check, sleep } from "k6";
import { Counter, Rate, Trend } from "k6/metrics";

const BASE_URL          = "http://localhost:6060";
const COUNT_ENDPOINT    = `${BASE_URL}/api/v1/product/product-count`;
const LIST_ENDPOINT     = `${BASE_URL}/api/v1/product/product-list`;   // /:page appended at runtime
const FILTER_ENDPOINT   = `${BASE_URL}/api/v1/product/product-filters`;

// ---------------------------------------------------------------------------
// Custom metrics
// ---------------------------------------------------------------------------

/** Total server errors (5xx) across all three steps */
const errorCount = new Counter("shop_errors");

/** Proportion of requests that resulted in a server error (5xx) */
const errorRate = new Rate("shop_error_rate");

/** Latency for GET /product-count */
const countLatency = new Trend("shop_count_latency", true);

/** Latency for GET /product-list/:page */
const listLatency = new Trend("shop_list_latency", true);

/** Latency for POST /product-filters */
const filterLatency = new Trend("shop_filter_latency", true);

/** End-to-end latency for the full three-step flow (sum of network time, excluding think-time) */
const shopE2ELatency = new Trend("shop_e2e_latency", true);

/** Number of products returned by the filter step — tracks query consistency */
const filteredProductCount = new Trend("shop_filter_result_count");

// ---------------------------------------------------------------------------
// Filter variations
//
// Each entry represents a realistic price-range a shopper might select from
// the sidebar.  The controller reads radio as [min, max] (inclusive) and
// checked as an array of category ObjectIds; an empty checked array means
// "all categories", which is the common first-filter action.
// ---------------------------------------------------------------------------
const PRICE_FILTERS = [
  { checked: [], radio: [0, 19]    },   // budget tier
  { checked: [], radio: [0, 39]    },   // entry tier
  { checked: [], radio: [0, 99]    },   // mid tier
  { checked: [], radio: [100, 299] },   // premium tier
  { checked: [], radio: [300, 999] },   // high-end tier
  { checked: [], radio: []         },   // no price filter (browse all)
];

// ---------------------------------------------------------------------------
// Load profile
//
// Models the shop-page hit rate during a peak shopping hour:
//   • Warm-up   : a small wave of early shoppers arrives             (1 min, 0→10 VUs)
//   • Ramp-up   : traffic rises as the peak hour gets under way      (2 min, 10→40 VUs)
//   • Sustained : steady concurrent shoppers browsing + filtering    (3 min, 40 VUs)
//   • Ramp-down : traffic subsides toward the end of the hour        (1 min, 40→0 VUs)
//
// 40 VUs is consistent with the login peak (also 40); most users who log in
// will land on the shop page and browse, so the two peaks should be comparable.
// ---------------------------------------------------------------------------

export const options = {
  stages: [
    { duration: "1m", target: 10 }, // warm-up
    { duration: "2m", target: 40 }, // ramp-up to peak
    { duration: "3m", target: 40 }, // sustained peak load
    { duration: "1m", target: 0  }, // ramp-down
  ],

  thresholds: {
    // 95 % of all HTTP requests across all three steps must complete within 500 ms
    http_req_duration: ["p(95)<500"],

    // Per-step latency budgets
    shop_count_latency:  ["p(95)<300", "p(99)<500"],    // simple estimatedDocumentCount
    shop_list_latency:   ["p(95)<500", "p(99)<1000"],   // paginated find + sort
    shop_filter_latency: ["p(95)<500", "p(99)<1000"],   // filtered find with optional range

    // End-to-end: count + list + filter network time (no think-time)
    shop_e2e_latency: ["p(95)<1200", "p(99)<2000"],

    // Server error rate (5xx) must stay below 1 %
    shop_error_rate: ["rate<0.01"],

    // At least 99 % of all k6 response checks must pass
    checks: ["rate>0.99"],
  },
};

// ---------------------------------------------------------------------------
// setup() — runs once before the load test begins
//
// Verifies all three endpoints are reachable and logs catalogue size so the
// run can be correlated with DB state when reviewing results later.
// ---------------------------------------------------------------------------
export function setup() {
  // --- product count preflight ---
  const countRes = http.get(COUNT_ENDPOINT, {
    headers: { Accept: "application/json" },
  });
  if (countRes.status >= 500) {
    throw new Error(
      `Preflight failed for product-count — server returned ${countRes.status}.`
    );
  }

  let total = 0;
  try { total = countRes.json().total || 0; } catch (_) {}

  // --- product list preflight (page 1) ---
  const listRes = http.get(`${LIST_ENDPOINT}/1`, {
    headers: { Accept: "application/json" },
  });
  if (listRes.status >= 500) {
    throw new Error(
      `Preflight failed for product-list — server returned ${listRes.status}.`
    );
  }

  // --- filter preflight (no filters applied) ---
  const filterRes = http.post(
    FILTER_ENDPOINT,
    JSON.stringify({ checked: [], radio: [] }),
    { headers: { "Content-Type": "application/json", Accept: "application/json" } }
  );
  if (filterRes.status >= 500) {
    throw new Error(
      `Preflight failed for product-filters — server returned ${filterRes.status}.`
    );
  }

  const totalPages = Math.ceil(total / 6) || 1;  // controller uses perPage = 6

  console.log(`Count endpoint  : ${COUNT_ENDPOINT}`);
  console.log(`List endpoint   : ${LIST_ENDPOINT}/:page`);
  console.log(`Filter endpoint : ${FILTER_ENDPOINT}`);
  console.log(`Catalogue size  : ${total} products across ${totalPages} page(s)`);
  console.log(`Filter profiles : ${PRICE_FILTERS.length}`);

  return { totalPages };
}


export default function ({ totalPages }) {
  // Each VU picks a page and a filter deterministically so the full catalogue
  // and all filter profiles are exercised evenly across iterations.
  const page   = ((__VU + __ITER) % totalPages) + 1;
  const filter = PRICE_FILTERS[(__VU + __ITER) % PRICE_FILTERS.length];

  // ---- Step 1: fetch total product count ----------------------------------
  //
  // The shop page calls this first to build pagination controls.

  const countRes = http.get(COUNT_ENDPOINT, {
    headers: { Accept: "application/json" },
    tags:    { name: "product_count" },
  });

  countLatency.add(countRes.timings.duration);

  const countServerError = countRes.status >= 500;
  errorRate.add(countServerError);
  if (countServerError) errorCount.add(1);

  check(countRes, {
    "count: status is 200":         (r) => r.status === 200,
    "count: response time < 300ms": (r) => r.timings.duration < 300,
    "count: content-type is JSON":  (r) =>
      (r.headers["Content-Type"] || "").includes("application/json"),
  });

  if (countRes.status === 200) {
    let body;
    try { body = countRes.json(); } catch (_) {
      check(null, { "count: body is valid JSON": () => false });
    }
    if (body) {
      check(body, {
        "count: success is true":  (b) => b.success === true,
        "count: total is a number":(b) => typeof b.total === "number" && b.total >= 0,
      });
    }
  }

  // Think-time: browser renders the pagination bar before fetching the list (0.5–1.5 s)
  sleep(0.5 + Math.random());

  // ---- Step 2: fetch one page of products ---------------------------------
  //
  // Simulates the user landing on (or navigating to) a specific results page.

  const listRes = http.get(`${LIST_ENDPOINT}/${page}`, {
    headers: { Accept: "application/json" },
    tags:    { name: "product_list" },
  });

  listLatency.add(listRes.timings.duration);

  const listServerError = listRes.status >= 500;
  errorRate.add(listServerError);
  if (listServerError) errorCount.add(1);

  check(listRes, {
    "list: status is 200":         (r) => r.status === 200,
    "list: response time < 500ms": (r) => r.timings.duration < 500,
    "list: content-type is JSON":  (r) =>
      (r.headers["Content-Type"] || "").includes("application/json"),
  });

  if (listRes.status === 200) {
    let body;
    try { body = listRes.json(); } catch (_) {
      check(null, { "list: body is valid JSON": () => false });
    }
    if (body) {
      check(body, {
        "list: success is true":          (b) => b.success === true,
        "list: products is an array":     (b) => Array.isArray(b.products),
        "list: at most 6 products":       (b) => !Array.isArray(b.products) || b.products.length <= 6,
      });

      if (Array.isArray(body.products) && body.products.length > 0) {
        const p = body.products[0];
        check(p, {
          "list: product has _id":   () => p._id !== undefined,
          "list: product has name":  () => typeof p.name === "string",
          "list: product has price": () => typeof p.price === "number",
          "list: photo is excluded": () => p.photo === undefined,
        });
      }
    }
  }

  // Think-time: user browses the product grid before opening the filter panel (1–3 s)
  sleep(1 + Math.random() * 2);

  // ---- Step 3: apply a price filter ---------------------------------------
  //
  // Simulates the user selecting a price range in the sidebar filter panel.

  const filterRes = http.post(
    FILTER_ENDPOINT,
    JSON.stringify(filter),
    {
      headers: {
        "Content-Type": "application/json",
        Accept:         "application/json",
      },
      tags: { name: "product_filters" },
    }
  );

  filterLatency.add(filterRes.timings.duration);

  const filterServerError = filterRes.status >= 500;
  errorRate.add(filterServerError);
  if (filterServerError) errorCount.add(1);

  // End-to-end: network time of all three steps (think-time excluded)
  shopE2ELatency.add(
    countRes.timings.duration +
    listRes.timings.duration  +
    filterRes.timings.duration
  );

  check(filterRes, {
    "filter: status is 200":         (r) => r.status === 200,
    "filter: response time < 500ms": (r) => r.timings.duration < 500,
    "filter: content-type is JSON":  (r) =>
      (r.headers["Content-Type"] || "").includes("application/json"),
  });

  if (filterRes.status === 200) {
    let body;
    try { body = filterRes.json(); } catch (_) {
      check(null, { "filter: body is valid JSON": () => false });
      sleep(1 + Math.random() * 2);
      return;
    }

    check(body, {
      "filter: success is true":      (b) => b.success === true,
      "filter: products is an array": (b) => Array.isArray(b.products),
    });

    if (Array.isArray(body.products)) {
      filteredProductCount.add(body.products.length);

      if (body.products.length > 0) {
        const p = body.products[0];
        check(p, {
          "filter: product has _id":   () => p._id !== undefined,
          "filter: product has price": () => typeof p.price === "number",
        });
      }
    }
  }

  // Think-time: user reviews filtered results before selecting a product (1–3 s)
  sleep(1 + Math.random() * 2);
}

export function teardown() {
  console.log("Shop browsing load test complete.");
}
