/**
 * Zhu Shiqi, A0271719X
 * Generated by Claude Code
 *
 * k6 Load Test — POST /api/v1/auth/register
 *
 * Simulates new-user registrations during a peak sign-up period.
 * Measures response times and throughput under normal registration load.
 *
 */

import http from "k6/http";
import { check, sleep } from "k6";
import { Counter, Rate, Trend } from "k6/metrics";

const BASE_URL = "http://localhost:6060";
const ENDPOINT = `${BASE_URL}/api/v1/auth/register`;

/** Total number of failed requests (5xx server errors) */
const errorCount = new Counter("register_api_errors");

/** Proportion of requests that resulted in a server error (5xx) */
const errorRate = new Rate("register_api_error_rate");

/** Per-request response latency for this endpoint */
const responseLatency = new Trend("register_api_latency", true);

/** Whether the server successfully created a new user account */
const registrationSucceeded = new Rate("register_success_rate");

// ---------------------------------------------------------------------------
// Load profile
//
// Models a registration spike during a promotional launch event:
//   • Warm-up   : early adopters trickle in                        (1 min, 0→5 VUs)
//   • Ramp-up   : sign-ups accelerate as word spreads              (2 min, 5→30 VUs)
//   • Sustained : peak registration rate during the promo window   (3 min, 30 VUs)
//   • Ramp-down : sign-up rate falls as the promo ends             (1 min, 30→0 VUs)
//
// Peak target is 30 VUs (lower than login/search) because registration is a
// one-time action that involves more DB writes (hashing + insert) and is
// naturally less frequent than repeat logins.
// ---------------------------------------------------------------------------

export const options = {
  stages: [
    { duration: "1m", target: 5  }, // warm-up
    { duration: "2m", target: 30 }, // ramp-up to peak
    { duration: "3m", target: 30 }, // sustained peak load
    { duration: "1m", target: 0  }, // ramp-down
  ],

  thresholds: {
    // 95 % of requests must complete within 500 ms
    http_req_duration: ["p(95)<500"],

    // 99 % of requests must complete within 1 s
    register_api_latency: ["p(99)<1000"],

    // Server error rate (5xx) must stay below 1 %
    register_api_error_rate: ["rate<0.01"],

    // At least 99 % of all response checks must pass
    checks: ["rate>0.99"],
  },
};

export default function () {
  // Each VU iteration uses a unique email derived from the VU index and
  // iteration counter so that every request attempts a fresh registration
  // rather than hitting the "already registered" branch.
  const email = `loadtest_vu${__VU}_iter${__ITER}@test.com`;

  const payload = JSON.stringify({
    name:     `Load Tester ${__VU}`,
    email:    email,
    password: "LoadTest@123",
    phone:    "12345678",
    address:  "123 Load Test Street",
    answer:   "loadtest",
  });

  const params = {
    headers: {
      "Content-Type": "application/json",
      Accept:         "application/json",
    },
    tags: { name: "register" },
  };

  const res = http.post(ENDPOINT, payload, params);

  // ---- record custom metrics ----
  responseLatency.add(res.timings.duration);

  // Only 5xx counts as an infrastructure error; 200 with success:false is app-level
  const serverError = res.status >= 500;
  errorRate.add(serverError);
  if (serverError) errorCount.add(1);

  // ---- HTTP-level checks ----
  check(res, {
    "status is 200":         (r) => r.status === 200,
    "response time < 500ms": (r) => r.timings.duration < 500,
    "content-type is JSON":  (r) =>
      (r.headers["Content-Type"] || "").includes("application/json"),
  });

  // ---- Response body checks ----
  if (res.status === 200) {
    let body;
    try {
      body = res.json();
    } catch (_) {
      check(null, { "body is valid JSON": () => false });
      sleep(3 + Math.random() * 4);
      return;
    }

    const succeeded = body.success === true;
    registrationSucceeded.add(succeeded);

    check(body, {
      "success flag is true": (b) => b.success === true,
      "message is present":   (b) => typeof b.message === "string",
      "user is returned":     (b) => b.user !== null && typeof b.user === "object",
    });

    if (succeeded && body.user) {
      check(body.user, {
        "user has _id":   (u) => u._id !== undefined,
        "user has name":  (u) => typeof u.name === "string",
        "user has email": (u) => typeof u.email === "string",
        "user has role":  (u) => u.role !== undefined,
      });
    }
  }

  // Think-time: a user who just registered reads a confirmation page (3–7 s)
  sleep(3 + Math.random() * 4);
}

export function setup() {
  // Preflight: verify the endpoint is reachable with a known-unique address
  const preflightEmail = `preflight_setup_${Date.now()}@test.com`;
  const res = http.post(
    ENDPOINT,
    JSON.stringify({
      name:     "Preflight User",
      email:    preflightEmail,
      password: "LoadTest@123",
      phone:    "12345678",
      address:  "123 Load Test Street",
      answer:   "loadtest",
    }),
    { headers: { "Content-Type": "application/json" } }
  );

  if (res.status >= 500) {
    throw new Error(
      `Preflight failed — server error ${res.status}.`
    );
  }

  let preflightStatus;
  try {
    preflightStatus = res.json().success ? "registered" : "app-level rejection";
  } catch (_) {
    preflightStatus = "non-JSON response";
  }

  console.log(`Target   : ${ENDPOINT}`);
  console.log(`Preflight: HTTP ${res.status} — ${preflightStatus}`);
  return {};
}

export function teardown() {
  console.log("Register load test complete.");
}
